BASE:
  Compositions: [[12, 24],[18,24],[4,24],[8,24],[24,24]] # Target compositions
  Elements: [O, Cu] # Elements
  Gpu: [0,1,2,3] # Available GPU IDs
  Iterations: 3 # Number of iterations
  Templates: <YOUR_TEMPLATES_PATH> # Template directory path
  Workdir: <YOUR_WORKDIR_PATH> # Working directory path
# CPU configuration
CPU:
  CPU IP: <YOUR_CPU_IP>
  CPU Port: <YOUR_CPU_PORT>
  CPU Username: <YOUR_CPU_USERNAME>
  CPU Working Directory: <YOUR_CPU_WORKDIR>
# Sampler configuration
SAMPLING:
  GA:
    RANDOMSEEDS:
      Activate: False # Whether to enable the random seed generator; a random seed file is required if disabled (False)
      Dimension: 0 # 0: cluster, 3: bulk
      Random Seeds Num: 20 # Number of random seeds (100)
      Random Seeds Path: <YOUR_RANDOM_SEEDS_PATH> # Random seed path
      Init Seeds Path: <YOUR_INIT_SEEDS_PATH> # Initial seed path
    USPEX:
      Dimension: 2 # 1:cluster, 2: surface, 3: bulk
      Generation Num: 3 # Number of GA generations
      Init Pop Size: 20 # Population size of the first generation
      Pop Size: 20 # Population size of each generation
      Calculator: DP # Calculator: DP/MACE
      Substrate: <YOUR_SUBSTRATE_PATH> # Substrate structure
      USPEX Env: <YOUR_USPEX_ENV_PATH> # Environment file
    POSTPROCESSING:
      # NN evaluator categories: accurate, candidate, failed
      Force Error Lower: 0.05
      Force Error Upper: 0.2
      # Energy&Force Filter, sp -> dft opt
      Max Filter Ratio: 0.8
      Max Filter Num: 50
      # Remove bad data points using the best model
      Energy Filter: 0.1
      Force Filter: 2
      # LCS processing
      LCS Process: False # Whether to perform LCS processing
      Type: slab # slab/cluster
      LCS Layers Num: 3 # Number of LCS layers for slabs
      LCS Radius: 5.0 # LCS radius for clusters
      # AIMD
      AIMD: False # Whether to use AIMD for additional continuous sampling
      MD Max Filter Ratio: 0.2 # Ratio of structures requiring MD sampling
      MD Max Filter Num: 10 # Maximum number of structures requiring MD sampling
      MD Init Data: <YOUR_MD_INIT_DATA_PATH> # Path to initial MD data
# Trainer configuration 1
TRAINER:
  Deepmd:
    # Data Path: <YOUR_DATA_PATH> # Initial data path
#    Initial Model: <YOUR_INIT_MODEL_PATH> # Initial model path (None)
    Train Ratio: 0.9 # Training set ratio (0.8)
