# Notes!
# config.yml, 键名均为小写, 值的大小写敏感且字符类型加单引号
#

db_path: './H_config.db'
work_path: './result'
save_log: true
print_log: false
engine: 'purevasp' # purevasp/asevasp/hybrid

ase:
  optimizer: 'BFGS' # BFGS/BFGSLine, BFGSLine不到万不得已不要用
  save_hessian: false  # 是否保存hessian矩阵, 不建议hybrid引擎开, 开启时降低nsteps到200以下
  maxstep: 0.2
  nsteps: 200  # 不要超过1000
  fmax: 0.05

mlp:
  task: 'F' # EF/F
  gpu_id: 7
  batch_size: 12
  vaild_ratio: 0.15
  loss_energy: 'mae'
  loss_force: 'ql2'
  checkpoint_load_path: './mlp_direct_h512_all.pt'
  only_vasp_ratio: 0.3

vasp:
  system: 'VaspJet' 
  #gga: 'RP'
  pp: 'PBE'
  xc: 'PBE'
  lreal: 'Auto'
  kpts: [ 1, 1, 1 ]
  #ldau_luj:
  #  Cr:
  #    L: 2
  #    U: 3.0
  #    J: 0.9
  # lmaxmix: 6
  # ispin: 1
  # isym: 0
  encut: 300
  ismear: 0
  sigma: 0.05
  algo: 'Fast'
  prec: 'Normal'
  nelm: 60
  nsw: 600
  ediff: 1.0e-4
  ediffg: -0.1
  symprec: 1.0e-5
  # ibrion: -1
  # potim: 0.2
  # isif: 3 # 3 hybrid
  nwrite: 1
  ncore: 4
  lwave: false
  lcharg: false
  txt: 'vaspout.txt'

slurm:
  slurm_time: '7-00:00:00'
  slurm_partition: 'CLUSTER'
  nodes: 1
  tasks_per_node: 1
  cpus_per_task: 24
  vasp_version: 'vasp_gam'
  slurm_setup:
    - 'source /home/fwtop/intel/parallel_studio_xe_2020.4.912/psxevars.sh intel64'
    - 'source /home/fwtop/intel/mpi2015/profile.d/mpi_intelmpi-5.0.2.044.sh'
    - 'ulimit -s unlimited'
    - 'export I_MPI_PIN_DOMAIN=omp'
    - 'MKL_DEBUG_CPU_TYPE=5'
    - 'MKL_CBWR=AVX2'
    - 'export PATH=/home/fwtop/Applications/vasp/vasp.6.3.2/bin:$PATH'
    - 'export VASP_PP_PATH=/home/fwtop/Applications/vasp/POTCAR'

